export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_INVALID_PAYLOAD: "MERGE_INVALID_PAYLOAD",
  MERGE_ABORTED: "MERGE_ABORTED",
  MERGE_STORAGE_FULL: "MERGE_STORAGE_FULL"
} as const;
