export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_BATCH_DUPLICATED: "MERGE_BATCH_DUPLICATED",
  MERGE_BATCH_INTERRUPTED: "MERGE_BATCH_INTERRUPTED",
  MERGE_PAYLOAD_INVALID: "MERGE_PAYLOAD_INVALID",
  MERGE_CONFLICT_UNRESOLVED: "MERGE_CONFLICT_UNRESOLVED"
} as const;
